### ISSUE TITLE
Couldn't run as the guide.

### ISSUE THREAD

**Issue by vonnyfly** [bartonhammond/snowflake#92] opened 2016-04-29 07:17 UTC
2016-04-29 15:11:50.060 [info][tid:com.facebook.React.JavaScript] Running application "snowflake" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2016-04-29 15:11:50.079 [error][tid:com.facebook.React.JavaScript] undefined is not an object (evaluating '_reactNativeRouterFlux2.default.Router')
2016-04-29 15:11:50.085 [fatal][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating '_reactNativeRouterFlux2.default.Router')

Like this:
![](http://ww4.sinaimg.cn/large/67dee169jw1f3dlh332oyj20km10uqb1.jpg)

**Comment by Antonhansel** [comment] 2016-04-30 03:49
Same issue here

**Comment by rbmedia** [comment] 2016-04-30 16:06
Same error for me too,  unfortunately I have not the skills to find out what is wrong (I wanted to learn from this app :)
line #145   const Router = connect()(RNRF.Router);

**Comment by bartonhammond** [comment] 2016-04-30 17:40
I'll take a look at all these issues tomorrow.  This is one of the pains of using so many Javascript libraries that are continuously changing - it's difficult to just keep a working app, working.

**Comment by rbmedia** [comment] 2016-04-30 21:10
thanks! - I spent some hours this week building  a login per Rest to a Drupal backend and was struggling with keeping the state of the user, when I discovered your app, it solves all my doubts and more.., it is amazing.

**Comment by oldashes** [comment] 2016-05-03 13:47
the same issue +1

**Comment by bartonhammond** [comment] 2016-05-03 13:48
Note that i am no longer maintaining this project - see README.  If someone fixes these issues I will merge a PR but that's the extent of my involvement now.

**Comment by rbmedia** [comment] 2016-05-03 14:15
I did the following to remove the error and access to the UI.
in snowflake.js :
line #27
I changed Route to "Router" - 
 line #145 is commented out (removed)
//   const Router = connect()(RNRF.Router);

after this I could access the APP.
Do not ask me more, I a just learning from there!

**Comment by bartonhammond** [comment] 2016-05-04 14:23
Please use stable release 1.0 [https://github.com/bartonhammond/snowflake/releases/tag/0.1.0](https://github.com/bartonhammond/snowflake/releases/tag/0.1.0 )

**Comment by rbmedia** [comment] 2016-05-04 14:51
Thanks for your update and all the best for your recovery!!!!

I am trying to figure out now, how to remove the warnings:
 "Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component."

the warnings are thrown from the first screen (I just change the orientation of the device and get 48).

by the way, I did learn a lot from your work! And have managed to login to a different backend with the old code yesterday! Thanks again

**Comment by wookiem** [comment] 2016-05-07 14:59
@rbmedia  @bartonhammond I've got a fix for the SetState warning issue.  I will issue a pull request tomorrow when I'm back at my computer.

**Comment by rbmedia** [comment] 2016-05-07 15:51
Hi wookiem
can you point me to the cause of the warnings?

**Comment by wookiem** [comment] 2016-05-07 16:01
In snowflake.js, add the following additional scene:
```
        <Scene key="InitialLoginForm"
                     component={Register}
                     title="Register" />
```

In getSessionToken() in authActions.js change:
  Actions.Register(); 
to:
 Actions.InitialLoginForm();

**Comment by rbmedia** [comment] 2016-05-07 19:04
Thanks wookiem, it works on the first view, but not if I change to "Forgot password" or "Already have an account", then I get teh warning again. I can not find what call produce those warnings

**Comment by wookiem** [comment] 2016-05-07 19:27
@rbmedia  So, when you launch Snowflake and immediately start cycling between Register / Forgot Password, etc. your seeing the warning?  I'm no longer seeing the error in my full app when I cycle between Register/Forget password...  I will have time tomorrow to do a pull request against Snowflake.

**Comment by rbmedia** [comment] 2016-05-07 20:05
Yes, after launching the App, I cycle to "Forgot Password" and by rotating the device I get the warning.
Without typing or doing anything else. the app version is 0.1.0.

**Comment by wookiem** [comment] 2016-05-07 21:31
Yes, when I rotate device, I'm getting the same error now.  Looks like this issue may be fixed by upgrading to RN 24.  If so, perhaps my changes aren't required.  https://github.com/aksonov/react-native-router-flux/issues/616

**Comment by wookiem** [comment] 2016-05-09 18:54
@rbmedia @bartonhammond 

I've made a couple more changes and I no longer have the error (even when I device rotate):

package.json:
"react-native": "0.24.0"
"react-native-router-flux": "3.22.0"

snowflake.js:
- remove type-"replace" from Login, Register and ForgotPassword scene.

npm test also runs cleanly.

I'm hesitant to issue a pull request at this stage because RN25 which is due out in 9 days may revert some of the changes.

**Comment by bartonhammond** [comment] 2016-05-10 00:17
@wookiem @rbmedia I think upgrading from RN 19 to 24 would be worth it.  

We would want to wait after RN 25 for a while anyway, for it to stabilize, so might as well get to a stabilzed 24.  Heck, there's already a RN 26.0-rc.

**Comment by wookiem** [comment] 2016-05-10 13:04
Ok, I will submit a pull request later today.

**Comment by rbmedia** [comment] 2016-05-11 14:37
Thank You wookiem!

**Comment by bartonhammond** [comment] 2016-05-12 15:55
Fixed with [https://github.com/bartonhammond/snowflake/releases/tag/0.1.1](https://github.com/bartonhammond/snowflake/releases/tag/0.1.1)

**Closed by bartonhammond** 2016-05-12 15:55 UTC
