### ISSUE TITLE
SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.

### ISSUE THREAD

**Issue by fones** [bartonhammond/snowflake#182] opened 2017-02-19 14:25 UTC
Got following error:

![image](https://cloud.githubusercontent.com/assets/2134294/23103186/46599642-f6b7-11e6-8f60-748e6af6b133.png)

node 7.5.0
android 6.0 

Can be related to this: https://github.com/facebook/react-native/issues/11389

**Comment by bartonhammond** [comment] 2017-02-27 21:54
I upgraded to https://github.com/bartonhammond/snowflake/releases/tag/0.2.1 and my Android installation and my GenyMotion and I am not able to reproduce this.

Please try upgrading everything mentioned and try again.  If you can reproduce it, let me know and I'll open this back up.  But for now, I'm closing.

Many thanks for checking out Snowflake!

**Closed by bartonhammond** 2017-02-27 21:54 UTC

**Comment by jwerlley** [comment] 2017-06-13 13:28
Just activate a JS Minify option in the Emulator Dev Settings

    In Emulator: Menu > Dev Settings > JS Minify ☑(active)

Here it worked only with this, I hope it has helped;)

**Comment by ycpatel813** [comment] 2017-11-14 02:35
@jwerlley Its great, but I am curious about to know the reason behind this issue. Can you elaborate with detail?

**Comment by Metroxe** [comment] 2018-05-04 18:15
+1
